---
name: dockerfile-lint

on:
  pull_request:
    paths:
      - 'docker/**'

permissions:
  contents: read

jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: 'docker/*Dockerfile'
          annotate: false
