---
name: dockerfile-lint

on:
  pull_request:
    paths:
      - 'docker/**'

permissions:
  contents: read

jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: 'docker/*Dockerfile'
          annotate: false
